# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leo Gau
email: me@leogau.org
description: Thoughts from Leo Gau
url: "http://leogau.org" # the base hostname & protocol for your site
twitter_username: leogau
github_username:  leogau

# Build settings
markdown: kramdown
highlighter: pygments
