# Site settings
title: Leo Gau
email: me@leogau.org
description: Thoughts from Leo Gau
url: "http://leogau.org" # the base hostname & protocol for your site
twitter_username: leogau
github_username:  leogau
permalink: /posts/:title


# Build settings
markdown: kramdown
highlighter: rouge
